# Generated by Django 3.0.7 on 2020-06-25 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('year_released', models.IntegerField()),
                ('ric_score', models.FloatField()),
                ('pat_score', models.FloatField()),
                ('ref_score', models.FloatField()),
                ('review_date', models.DateField(default=datetime.date(2020, 6, 25))),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
